### ISSUE TITLE
Ошибка при импорте simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found

### ISSUE THREAD

**Issue by andymark-by** [carono/yii2-1c-exchange#4]
При импорте файла всегда вылетает такая ошибка

```
yii\base\ErrorException: simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in /var/www/www-root/data/www/corono.fullstack.by/vendor/carono/commerceml/src/CommerceML.php:108
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'simplexml_load_...', '/var/www/www-ro...', 108, Array)
#1 /var/www/www-root/data/www/corono.fullstack.by/vendor/carono/commerceml/src/CommerceML.php(108): simplexml_load_string('/var/www/www-ro...')
#2 /var/www/www-root/data/www/corono.fullstack.by/vendor/carono/commerceml/src/CommerceML.php(71): Zenwalker\CommerceML\CommerceML->loadXml('/var/www/www-ro...')
#3 /var/www/www-root/data/www/corono.fullstack.by/vendor/carono/yii2-1c-exchange/controllers/ApiController.php(164): Zenwalker\CommerceML\CommerceML->loadImportXml('/var/www/www-ro...')
#4 /var/www/www-root/data/www/corono.fullstack.by/vendor/carono/yii2-1c-exchange/controllers/ApiController.php(264): carono\exchange1c\controllers\ApiController->parsingImport('/var/www/www-ro...')
#5 [internal function]: carono\exchange1c\controllers\ApiController->actionImport('catalog', 'import.xml')
#6 /var/www/www-root/data/www/corono.fullstack.by/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /var/www/www-root/data/www/corono.fullstack.by/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#8 /var/www/www-root/data/www/corono.fullstack.by/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('import', Array)
#9 /var/www/www-root/data/www/corono.fullstack.by/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('exchange/api/im...', Array)
#10 /var/www/www-root/data/www/corono.fullstack.by/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 /var/www/www-root/data/www/corono.fullstack.by/web/index.php(13): yii\base\Application->run()
#12 {main}
```

**Comment by carono** [comment]
Скинь xml файлы, чтобы проверить. Можно в 1С сделать выгрузку в каталог или в конфиге модуля поставить debug=1 и после импорта в папке @runtime/1c_exchange будут эти файлы

**Comment by carono** [comment]
Что-то мне подсказывает, что всё решилось само.

**Comment by Ayurka** [comment]
Здравствуйте! что за метод addPivot?

**Comment by carono** [comment]
> Здравствуйте! что за метод addPivot?

Это метод из трайта в пакете https://github.com/carono/yii2-migrate, в данном случае просто сохраняет в сводную таблицу id модели
